### ISSUE TITLE
Version 3.1 No Longer Tagged

### ISSUE THREAD

**Issue by jimrubenstein** [stepanenko3/nova-json#18]
Version 3.1 is gone, and as such, composer will throw errors when running `composer update`, as that version is no longer tagged.

It looks like you reset the entire commit history and wiped everything from the previous package out from under this new 4.0 release.

When you did that, you completely destroyed people's ability to update. And, if this [4.0] version is breaking/not backwards compatible, people are stuck either using old dependencies, or removing yours.

I'd consider putting the deprecated version somewhere (backfilling here, or under a new git repo) so those of us that still use this package can manage to maintain our projects and migrate within our production schedule, instead of yours.

**Comment by Epizefiri** [comment]
I agree with you, it's pure madness

**Comment by jimrubenstein** [comment]
bumping this

**Comment by stepanenko3** [comment]
@Jimrubenstein @Epizefiri

This package was created for your own projects. The one you're talking about was a copy of another repository with updates for Nova 4

You can find information about the source of the package in the vendor/stepanenko3/nova-json/README.md file and reuse it if necessary.

This package is a completely new implementation, without any references to the previous package
