### ISSUE TITLE
Extra data written to JSON string

### ISSUE THREAD

**Issue by borcherds-ralph** [stepanenko3/nova-json#2]
I have a JSON column with this as the default data string

{"payment":{"agree":0},"independentContract": {"path":"","role":null,"agree":0,"signed":null,"created_at":null,"ip_address":null,"invite_status":"Pending"}}

When I update the record through Nova, the string is written like this

{"":"<b>independentContract</b>","payment":{"agree":"0"},"independentContract":{"path":"path","role":null,"agree":"0","signed":null,"created_at":"","ip_address":null,"invite_status":"Active"}}

This is the JSON definition in Nova

JSON::make('relationship', [
          JSON::make('payment', [
                 Number::make('agree'),
           ]),
           JSON::make('independentContract', 'independentContract', [
                    Text::make('path'),
                    Text::make('role'),
                    Number::make('agree'),
                    Text::make('signed'),
                    DateTime::make('Create At', 'created_at'),
                    Text::make('ip_address'),
                    Select::make('invite_status')->options([
                        'Active' => 'Active',
                        'Hold' => 'Hold',
                        'Pending' => 'Pending',
                        'Terminated' => 'Terminated'
                    ])->default('Pending'),
           ]),
])

This part of the JSON data does not belong and I am having a hard time removing it.

"":"<b>independentContract</b>"

This is what the screen display looks like
![json-issue](https://user-images.githubusercontent.com/607770/179329828-f1d98d47-53d6-4cac-a3b7-7780bfa2026e.png)

**Comment by stepanenko3** [comment]
@borcherds-ralph, thanks for issue

I will try to fix this problem in the coming days

**Comment by stepanenko3** [comment]
Hi, @borcherds-ralph 

I fixed it in the new version https://github.com/stepanenko3/nova-json/releases/tag/v3.1.0
