### ISSUE TITLE
displayUsing not working

### ISSUE THREAD

**Issue by zsoltjanes** [stepanenko3/nova-json#20]
I have the following code, and i only see the integer insted of the currency name, the display using function not called or i dont know.

`JsonRepeatable::make('Price', 'meta->price')
                ->fullWidth()
                ->rules([
                    'required',
                    'array',
                    'min:1',
                ])
                ->fields([
                    Select::make('Currency', 'currency_id')
                        ->rules('required')
                        ->options(Currency::all())
                        ->displayUsing(function ($name) {
                            return Currency::first($name)->name;
                        }),
         ])->hideFromIndex(),`

**Comment by saberhashemzadeh** [comment]
you can use this code:
`JsonRepeatable::make('Price', 'meta->price') ->fullWidth() ->rules([ 'required', 'array', 'min:1', ]) ->fields([ Select::make('Currency', 'currency_id') ->rules('required') ->options(Currency::all())])->resolveUsing(function ($fields){
                    $custom_values = [];
                    foreach ($fields as $field)
                    {
                        $field['currency_id'] = Currency::where('currency_id', $field['currency_id'])->first()->name;
                        $custom_values[] = $field;
                    }
                    return $custom_values;
                })->onlyOnDetail(),
JsonRepeatable::make('Price', 'meta->price') ->fullWidth() ->rules([ 'required', 'array', 'min:1', ]) ->fields([ Select::make('Currency', 'currency_id') ->rules('required') ->options(Currency::all())])->hideFromDetail(),`

**Comment by stepanenko3** [comment]
@saberhashemzadeh thanks
I think I'll analyze it later and add it to readme
