### ISSUE TITLE
Ability to set the showHeading variable

### ISSUE THREAD

**Issue by steven-pqp** [stepanenko3/nova-json#3]
Would it be possible to make the showHeading variable configurable to choose whether or not to display a header?

It is true by default and it is impossible to change its state

Thanks

**Comment by stepanenko3** [comment]
@steven-pqp,
Thank you for your idea. I’ll do it in a few days

**Comment by stepanenko3** [comment]
Hi, @steven-pqp
I did it in a new version

```php
JSON::make('Settings', 'settings', [
    Heading::make('Demo'),

    Boolean::make('Animated', 'animated'),

    JSON::make('Telegram', 'telegram', [
        Text::make('Telegram username', 'username'),
    ], false),
], true),
```
