### ISSUE TITLE
Currency field

### ISSUE THREAD

**Issue by KickSchutte67** [stepanenko3/nova-json#8]
Hi!

When filling the Currency field I get null as response. I do not get this when using the Text field. How do I solve this issue?

<img width="971" alt="Screenshot 2022-12-14 at 13 07 12" src="https://user-images.githubusercontent.com/31417270/207591327-bca96ad8-38b6-4bca-be11-dbacceb1b05a.png">

**Comment by stepanenko3** [comment]
@KickSchutte67 

I have completely redesigned the JSON package, please check the documentation
