### ISSUE TITLE
Fields not showing

### ISSUE THREAD

**Issue by HeadStudios** [stepanenko3/nova-json#9]
Hi,

I have installed package and cast my json field - imported with use statement t the top as so:

```php
use Laravel\Nova\Fields\Text;
use Stepanenko3\NovaJson\JSON;

// other use statements and code

public function fields(NovaRequest $request)
    {
        return [

            ID::make()->hideFromIndex()->sortable(),
            JSON::make('Custom Fields', [
                Text::make('Field 1', 'field1'),
                Text::make('Field 2', 'field2'),
                // Add more fields as needed
            ]),
```

However unfortunately this has not worked for me - on Nova detail and edit it shows label name but no text fields.

https://share.getcloudapp.com/xQuRodN4

Any idea why would be much appreciated.

**Comment by stepanenko3** [comment]
@HeadStudios  

I have completely redesigned the JSON package, please check the documentation
